name: Extract  snowflow

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'  # Ejecutar cada minuto
jobs:
    extract:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10' 
                cache: 'pip' # caching pip dependencies
            - run: pip install -r requirements.txt
            - run: python ./scripts/extract_from_snowflake.py
            - name: Extrae data snowflake
              uses: actions/upload-artifact@v4
              with:
                name: subte_data_raw
                path: subte_data_raw.csv

