name: Extract data from Snowflake

on:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  extract_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install snowflake-connector-python

    - name: Extract data and save as CSV
      env:
        SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
        SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
      run: python extract_data.py

