name: Extract from Snowflake

on:
  workflow_dispatch:
  
jobs:
  extract_from_snowflake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract data from Snowflake
        run: |
          python scripts/extract_from_snowflake.py
        env:
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_DATABASE: 'SOURCE'
          SNOWSQL_SCHEMA: 'RAW'
          SNOWSQL_TABLE: 'SUBTEDATA'

      - name: Save extracted data as CSV
        run: mv extracted_data.csv datos_snow.csv
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add extracted data from Snowflake"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
